name: Playwright Tests

on:
  push:
    branches: [ "main", "master", "review" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Copy env file
        run: cp .env.example .env

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          BURGER_API_URL: https://norma.nomoreparties.space/api
